namespace LongevityWorldCup.Website.Business
{
    public static class Flags
    {
        public static readonly List<string> Flag =
        [
            "Cyberspace",
            "Abkhazia",
            "Adjara",
            "Afghanistan",
            "Ainu Mosir",
            "Aksai Chin",
            "Aland Islands",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andalusia",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctic Claims",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Artsakh",
            "Aruba",
            "Ascension Island",
            "Asgardia",
            "Ashmore and Cartier Islands",
            "Atlantium",
            "Australia",
            "Austria",
            "Azad Kashmir",
            "Azerbaijan",
            "Azores",
            "Bahamas",
            "Bahrain",
            "Bajo Nuevo Bank",
            "Balochistan",
            "Bangladesh",
            "Barbados",
            "Basque Country",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Biafra",
            "Bolivia",
            "Bonaire",
            "Bosnia and Herzegovina",
            "Botswana",
            "Bougainville",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Buryatia",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Canary Islands",
            "Catalonia",
            "Cayman Islands",
            "Central African Republic",
            "Ceuta",
            "Chad",
            "Chagos Archipelago",
            "Chechnya",
            "Cheju",
            "Chile",
            "China",
            "Chittagong Hill Tracts",
            "Christiania",
            "Christmas Island",
            "Clipperton Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Conch Republic",
            "Congo",
            "Cook Islands",
            "Coral Sea Islands",
            "Corsica",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Curaçao",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Druze Regions",
            "Ecotopia",
            "Ecuador",
            "Eelam Tamil",
            "Egypt",
            "El Salvador",
            "Empire of Poyais",
            "Enclava",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Falkland",
            "Faroe Islands",
            "Federal Republic of Antarctica",
            "Fiji",
            "Finland",
            "First Nations Reserves",
            "Flemish Community",
            "Forvik",
            "France",
            "French Community of Belgium",
            "French Guiana",
            "French Polynesia",
            "French Southern and Antarctic Lands",
            "Gabon",
            "Gagauzia",
            "Galicia",
            "Galápagos Islands",
            "Gambia",
            "Gay and Lesbian Kingdom of the Coral Sea Islands",
            "Georgia",
            "German-speaking Community of Belgium",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Gilgit-Baltistan",
            "Global Country of World Peace",
            "Grand Duchy of Flandrensis",
            "Grand Duchy of Westarctica",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Hajduk Republic of Mijak",
            "Heard Island",
            "Hokkaido",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "Ile Amsterdam",
            "Ile Saint-Paul",
            "Iles Crozet",
            "India",
            "Indonesia",
            "Infinita",
            "Inner Mongolia",
            "Inuit Regions of Canada",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Isle of Wight",
            "Israel",
            "Italy",
            "Jamaica",
            "Jammu and Kashmir",
            "Jan Mayen",
            "Japan",
            "Jarvis Island",
            "Jeju Island",
            "Jersey",
            "Johnston Atoll",
            "Jordan",
            "Joseon Empire",
            "Judea and Samaria",
            "Kaliningrad",
            "Karakalpakstan",
            "Kazakhstan",
            "Kenya",
            "Kerguelen Islands",
            "Kingdom of EnenKio",
            "Kingman Reef",
            "Kiribati",
            "Korea, North",
            "Korea, South",
            "Kosovo",
            "Kurdistan",
            "Kuwait",
            "Kyrgyzstan",
            "Ladakh",
            "Lakota Nation",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Liberland",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Lord Howe Island",
            "Luxembourg",
            "Macaronesia",
            "Macau",
            "Madagascar",
            "Madeira",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marsa Alam",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "McDonald Islands",
            "Melilla",
            "Mexico",
            "Micronations like Elgaland-Vargaland",
            "Micronesia",
            "Midway Atoll",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Nagorno-Karabakh",
            "Namibia",
            "Nauru",
            "Navassa Island",
            "Naxcivan",
            "Nepal",
            "Netherlands",
            "Nevis",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "North Dumpling Island",
            "North Macedonia",
            "Northern Cyprus",
            "Northern Ireland",
            "Northern Mariana Islands",
            "Norway",
            "Nunavut",
            "Ogaden",
            "Oman",
            "Orkney Islands",
            "Other Antarctica Claims",
            "Pakistan",
            "Palau",
            "Palestine",
            "Palmyra Atoll",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn Islands",
            "Poland",
            "Portugal",
            "Principality of Aigues-Mortes",
            "Principality of Filettino",
            "Principality of Freedonia",
            "Principality of Hutt River",
            "Principality of Ladonia",
            "Principality of New Utopia",
            "Principality of Outer Baldonia",
            "Principality of Pontinha",
            "Principality of Redonda",
            "Principality of Seborga",
            "Principality of Snake Hill",
            "Principality of Talossa",
            "Principality of Wy",
            "Prospera",
            "Puerto Rico",
            "Qatar",
            "Rapa Nui (Easter Island)",
            "Republic of Anarchistan",
            "Republic of Cospaia",
            "Republic of Jamtland",
            "Republic of Kugelmugel",
            "Republic of Lakotah",
            "Republic of Minerva",
            "Republic of Molossia",
            "Republic of Rose Island",
            "Republic of Uzupis",
            "Republic of Vevcani",
            "Republic of West Papua",
            "Republika Srpska",
            "Reunion",
            "Rojava",
            "Romania",
            "Ross Dependency",
            "Russia",
            "Rwanda",
            "Ryukyu Islands",
            "Saba",
            "Sahrawi Arab Democratic Republic",
            "Saint Barthelemy",
            "Saint Eustatius",
            "Saint Helena",
            "Saint Kitts",
            "Saint Lucia",
            "Saint Martin",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Sardinia",
            "Saudi Arabia",
            "Saugeais Republic",
            "Scotland",
            "Sealand",
            "Senegal",
            "Serbia",
            "Serranilla Bank",
            "Seychelles",
            "Shetland Islands",
            "Sicily",
            "Sierra Leone",
            "Singapore",
            "Sint Maarten",
            "Slovakia",
            "Slovenia",
            "Socotra",
            "Solomon Islands",
            "Somalia",
            "Somaliland",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "South Ossetia",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "The Other World Kingdom",
            "Tibet",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Transnistria",
            "Transylvania",
            "Trinidad and Tobago",
            "Tristan da Cunha",
            "Tunisia",
            "Turkey",
            "Turkish Republic of Northern Cyprus",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "U.S. Virgin Islands",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Vitalia",
            "Vojvodina",
            "Wake Island",
            "Wales",
            "Wallis and Futuna",
            "Wallonia",
            "Waveland",
            "Western Sahara",
            "Whangamomona Republic",
            "Xinjiang Uyghur Autonomous Region",
            "Yemen",
            "Zambia",
            "Zanzibar",
            "Zimbabwe",
            "Zomia"
        ];
    }
}